### ISSUE TITLE
Jupyter cannot open MainCode.ipynb

### ISSUE THREAD

**Issue by shantanukarve** [Deckstar/Multifractal-Model-of-Asset-Returns-MMAR-for-Thesis#1]
Hi,

I cloned the repository and tried to use Jupyter to run it with the command:
jupyter notebook MAIN\ CODE.ipynb

It returns the error:
Unreadable Notebook: /home/shantanu/Multifractal-Model-of-Asset-Returns-MMAR-for-Thesis/MAIN CODE.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...')

So I used an online JSONlint to validate the JSON and it tells me that 
Error: Parse error on line 12822:
...d.read_csv(\"~"				YOUR USERNAME HERE "
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

Any ideas on this ? Thanks in advance for your help.
Shantanu Karve

**Comment by Deckstar** [comment]
Hello!

That was pretty weird. Sorry about that, don't know how that got in there. Basically some quote marks were missing backslashes (" instead of \\") so JSON was not being parsed.

I've fixed it and uploaded the latest version, so please try again. It should work now :)
